# Array creation and visualization

In [1]:
import numpy as np

In [3]:
x = np.empty([3, 3], np.uint8)
x

array([[ 26,   0,   0],
       [  0,  25,   0],
       [  0,   0, 224]], dtype=uint8)

In [4]:
#identity matrix
y = np.eye(5, dtype = np.uint8)
y

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=uint8)

In [5]:
#shifting the positions of 1 from the identity matrix
#upwards
y = np.eye(5, dtype = np.uint8, k = 1)
y

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]], dtype=uint8)

In [6]:
#downwards
y = np.eye(5, dtype = np.uint8, k = -1)
y

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]], dtype=uint8)

In [8]:
#two matrices of 5 x 5 consisting of ones only
y = np.ones((2,5,5), dtype = np.uint16)
y

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=uint16)

In [9]:
x = np.full((2,5), dtype = np.uint16, fill_value=5)
x

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]], dtype=uint16)