# Numpy and Visualizations

In [1]:
import numpy as np

In [2]:
l1 = [1,2,3,4,5]
x = np.array(l1, np.int16) # x = np.array(l1, dtype = np.int15)

In [3]:
type(x)

numpy.ndarray

In [4]:
x[0]

1

In [5]:
x[4]

5

In [6]:
x[-1]

5

In [7]:
#multi dimensional data
x1 = np.array([[1,2,3],[4,5,6]], np.int8)

In [8]:
x1

array([[1, 2, 3],
       [4, 5, 6]], dtype=int8)

In [12]:
#accessing elements in the multidimensional data
x1[0,2]

3

In [11]:
x1[1,2]

6

In [13]:
#accessing entire rows and columns
x1[:, 0]

array([1, 4], dtype=int8)

In [14]:
x1[:, 1]

array([2, 5], dtype=int8)

In [15]:
x1[1, :] #accessing all elements in the second row

array([4, 5, 6], dtype=int8)

In [16]:
x1[0, :] #accessing all elements in the first row

array([1, 2, 3], dtype=int8)

In [17]:
x1 = np.array([[[1,2,3],[4,5,6]],[[0, -1, -2], [-3, -4, -5]]], np.int8)
x1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 0, -1, -2],
        [-3, -4, -5]]], dtype=int8)

In [18]:
x1[0,0,0]

1

In [19]:
x1[-1,0,0]

0

In [20]:
x1[-1,-1,-1]

-5

# Properties of Ndarray

In [24]:
x2 = np.array([[[1,2,3],[4,5,6]],[[0, -1, -2], [-3, -4, -5]], [[0, 0, 1], [-1, -3, 4]]], np.int8)
x2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 0, -1, -2],
        [-3, -4, -5]],

       [[ 0,  0,  1],
        [-1, -3,  4]]], dtype=int8)

In [26]:
#number of dimensions
x2.ndim

3

In [27]:
x2.shape

(3, 2, 3)

In [28]:
x2.dtype

dtype('int8')

In [29]:
x2.size

18

In [30]:
#obtaining the transpose
x2.T

array([[[ 1,  0,  0],
        [ 4, -3, -1]],

       [[ 2, -1,  0],
        [ 5, -4, -3]],

       [[ 3, -2,  1],
        [ 6, -5,  4]]], dtype=int8)

# Numpy Constraints

In [31]:
np.inf #infinity

inf

In [32]:
np.NAN #not a number

nan

In [33]:
np.NINF #negative infinity

-inf

In [34]:
np.NZERO #negative zero

-0.0

In [35]:
np.PZERO #positive zero

0.0

In [36]:
np.e

2.718281828459045

In [37]:
np.pi

3.141592653589793

In [38]:
np.euler_gamma

0.5772156649015329